export default {
  accountForm: {
    modal: {
      addTitle: 'Add account',
      editTitle: 'Edit account',
      cancel: 'Cancel',
      next: 'Next',
      previous: 'Previous',
      create: 'Create',
      creating: 'Creating...',
      update: 'Update',
      updating: 'Updating...'
    },
    steps: {
      basicInfo: 'Basic information',
      authorization: 'Authorization'
    },
    platform: {
      selectPlatform: 'Select platform',
      selectSpecificType: 'Select platform type:',
      official: 'Official',
      standardApi: 'Standard API',
      gptSeries: 'GPT series',
      droidDedicated: 'Droid dedicated'
    },
    addMethod: {
      label: 'Add method',
      oauth: 'OAuth authorization',
      usageVisible: 'Usage visible',
      setupToken: 'Setup Token',
      longValidity: 'long validity',
      manualAccessToken: 'Enter Access Token manually',
      apiKeyMultiple: 'Use API Key (multiple supported)'
    },
    basic: {
      accountName: 'Account name',
      accountNamePlaceholder: 'Set an easy-to-recognize account name',
      description: 'Description (optional)',
      descriptionPlaceholder: "Describe this account's purpose...",
      accountType: 'Account type',
      sharedAccount: 'Shared account',
      dedicatedAccount: 'Dedicated account',
      groupScheduling: 'Group scheduling',
      accountTypeHelp:
        'Shared accounts are available to all API keys; dedicated accounts are only available to specific API keys; group scheduling accounts are dispatched within their groups.'
    },
    expiration: {
      label: 'Expiration time (optional)',
      never: 'Never expires',
      days30: '30 days',
      days90: '90 days',
      days180: '180 days',
      days365: '365 days',
      customDate: 'Custom date',
      expiresAt: 'Expires on {date}',
      neverExpires: 'Account never expires',
      help: 'Set the expiration time for Claude Max/Pro subscriptions. This account will stop being scheduled after it expires.'
    },
    groups: {
      select: 'Select group *',
      empty: 'No groups available',
      memberCount: '{count} members',
      createNew: 'Create group'
    },
    geminiProject: {
      label: 'Project ID (optional)',
      placeholder: 'Example: verdant-wares-464411-k9',
      title: 'Google Cloud/Workspace accounts require a project ID',
      description:
        'Some Google accounts, especially accounts linked to Google Cloud, may be recognized as Workspace accounts and require an additional project ID.',
      howToGet: 'How to get the project ID:',
      visit: 'Visit',
      copyProjectId: 'Copy the Project ID, usually a string value',
      warning: 'Copy the Project ID, not the Project Number.',
      tip: 'Tip:',
      tipText:
        'If this is a regular personal account not linked to Google Cloud, leave this field blank.'
    },
    bedrock: {
      credentialType: 'Credential type *',
      accessKey: 'AWS Access Key',
      bearerTokenLongLived: 'Bearer Token',
      accessKeyHelp:
        'Authenticate with AWS Access Key ID and Secret Access Key. Temporary credentials are supported.',
      bearerTokenHelp:
        'Authenticate with a Bearer Token generated by AWS Bedrock API Keys. It is simpler and has a smaller permission scope.',
      credentialTypeLocked:
        'Credential type cannot be changed in edit mode. Recreate the account to switch types.',
      accessKeyId: 'AWS Access Key ID',
      accessKeyIdRequired: 'AWS Access Key ID {required}',
      secretAccessKey: 'AWS Secret Access Key',
      secretAccessKeyRequired: 'AWS Secret Access Key {required}',
      sessionToken: 'Session token (optional)',
      keepExistingCredential: 'Leave blank to keep the existing credential',
      keepExistingAccessKeyId: 'Leave blank to keep the existing Access Key ID',
      keepExistingSecretAccessKey: 'Leave blank to keep the existing Secret Access Key',
      keepExistingSessionToken: 'Leave blank to keep the existing Session Token',
      enterAccessKeyId: 'Enter AWS Access Key ID',
      enterSecretAccessKey: 'Enter AWS Secret Access Key',
      enterSessionToken: 'Enter the session token if using temporary credentials',
      sessionTokenHelp: 'Only required when using temporary AWS credentials',
      bearerToken: 'Bearer Token {required}',
      keepExistingBearerToken: 'Leave blank to keep the existing Bearer Token',
      enterBearerToken: 'Enter AWS Bearer Token',
      bearerTokenInfoTitle: 'Bearer Token notes:',
      bearerTokenInfo1: 'Enter the Bearer Token generated by AWS Bedrock API Keys',
      bearerTokenInfo2:
        'Bearer Token access is limited to Bedrock services and has a smaller permission scope',
      bearerTokenInfo3: 'Simpler than Access Key and does not require a Secret Key',
      reference: 'Reference:',
      awsDocs: 'AWS official documentation',
      region: 'AWS region *',
      regionPlaceholder: 'Example: us-east-1',
      commonRegions: 'Common AWS regions:',
      regionCodeHelp: 'Enter the full region code, such as us-east-1',
      regionEastUs: 'us-east-1 (US East)',
      regionWestUs: 'us-west-2 (US West)',
      regionIreland: 'eu-west-1 (Europe Ireland)',
      regionSingapore: 'ap-southeast-1 (Singapore)',
      regionTokyo: 'ap-northeast-1 (Tokyo)',
      regionFrankfurt: 'eu-central-1 (Frankfurt)',
      defaultModel: 'Default main model (optional)',
      defaultModelHelp:
        'Leave blank to use the system default model. Inference profile IDs and ARNs are supported.',
      modelConfigTitle: 'Bedrock model configuration:',
      supportInferenceProfileId: 'Inference Profile ID supported (recommended)',
      supportApplicationInferenceProfileArn: 'Application Inference Profile ARN supported',
      commonModel: 'Common model: us.anthropic.claude-sonnet-4-20250514-v1:0',
      defaultModelSystem: 'Leave blank to use the configured system default model',
      smallFastModel: 'Small fast model (optional)',
      smallFastModelHelp:
        'Lightweight model for fast responses. Leave blank to use the system default.'
    },
    azureOpenAI: {
      endpoint: 'Azure Endpoint',
      endpointRequired: 'Azure Endpoint *',
      endpointHelp:
        'Azure OpenAI resource endpoint URL, format: https://your-resource.openai.azure.com',
      apiVersion: 'API version',
      apiVersionHelp:
        'Azure OpenAI API version. The latest stable version 2024-02-01 is used by default.',
      deploymentName: 'Deployment name',
      deploymentNameRequired: 'Deployment name *',
      deploymentNameHelp: 'Deployment name created in Azure OpenAI Studio',
      apiKey: 'API Key',
      apiKeyRequired: 'API Key *',
      apiKeyPlaceholder: 'Enter Azure OpenAI API Key',
      apiKeyHelp: 'API key from the Azure portal',
      supportedModels: 'Supported models',
      supportedModelsHelp: 'Select model types supported by this deployment'
    },
    rateLimit: {
      label: 'Rate limiting',
      enable: 'Enable rate limiting',
      enableHelp:
        'When enabled, scheduling pauses for a period after the account returns a 429 error.',
      duration: 'Rate limit duration (minutes)',
      durationPlaceholder: 'Default: 60 minutes',
      durationHelp: 'How long scheduling is paused after the account is rate limited.'
    },
    quota: {
      dailyLimit: 'Daily quota limit ($)',
      unlimitedPlaceholder: '0 means unlimited',
      dailyLimitHelp: 'Set the daily usage quota. 0 means unlimited.',
      resetTime: 'Quota reset time',
      resetTimeHelp: 'Time when the daily quota resets automatically',
      todayUsage: "Today's usage",
      remaining: 'Remaining: ${amount}',
      usedPercent: '{percent}% used',
      maxConcurrentTasks: 'Maximum concurrent tasks',
      maxConcurrentTasksHelp: 'Limit concurrent requests for this account. 0 means unlimited.'
    },
    modelRestrictions: {
      label: 'Model restrictions (optional)',
      whitelist: 'Model whitelist',
      mapping: 'Model mapping',
      whitelistHelp:
        'Select models allowed to use this account. Leave empty to support all models.',
      selectedCount: '{count} models selected',
      supportsAllModels: 'Supports all models',
      mappingHelp:
        'Configure model mappings. The left side is the client-requested model, and the right side is the model actually sent to the API.',
      sourceModelPlaceholder: 'Original model name',
      targetModelPlaceholder: 'Mapped model name',
      addMapping: 'Add model mapping'
    },
    userAgent: {
      customOptional: 'Custom User-Agent (optional)',
      custom: 'Custom User-Agent',
      passthroughPlaceholder: 'Leave blank to pass through the client User-Agent',
      passthroughOriginalPlaceholder: 'Leave blank to pass through the original request User-Agent',
      passthroughHelp:
        'When left blank, the client User-Agent is used automatically. Only set this when a fixed UA is required.',
      droidDefaultHelp: 'Leave blank to use the default factory-cli/0.32.1. Customize if needed.'
    },
    upstreamErrors: {
      label: 'Upstream error handling',
      disableAutoProtection: 'Do not automatically pause scheduling on upstream errors',
      help: 'When checked, upstream errors such as 401/400/429/529 are only logged and passed through; they do not automatically disable or rate limit the account.'
    },
    openaiResponses: {
      baseApi: 'API base URL *',
      baseApiPlain: 'API base URL',
      baseApiHelp:
        'Base URL for a third-party OpenAI-compatible API. Do not include a concrete path.',
      apiKey: 'API key *',
      apiKeyPlain: 'API key',
      keepExistingApiKey: 'Leave blank to keep the existing API Key',
      apiKeyHelp: 'API key provided by the third-party service',
      providerEndpoint: 'Provider endpoint type',
      endpointResponsesRecommended: 'Responses (recommended)',
      endpointAuto: 'Auto (keep original path)',
      endpointHelp:
        'Specify the endpoint type supported by the provider. Responses routes all requests to Responses and converts /v1/chat/completions requests automatically; Auto keeps the original client request path.'
    },
    geminiApi: {
      baseUrl: 'API base URL *',
      baseUrlPlain: 'API base URL',
      apiKey: 'API key *',
      apiKeyPlain: 'API key',
      keepExistingApiKey: 'Leave blank to keep the existing API Key',
      formatsHelp: 'Three formats are supported and detected automatically:',
      modelsSuffix: 'Ends with /models:',
      templateMode: 'Template mode:',
      domain: 'Domain:',
      autoAppendModels: 'Automatically appends /v1beta/models',
      apiKeyHelp: 'API key from Google AI Studio'
    },
    claudeOptions: {
      subscriptionType: 'Subscription type',
      proUnsupportedOpus4: 'Pro accounts do not support Claude Opus 4 models',
      autoStopNearFiveHourLimit:
        'Automatically stop scheduling when 5-hour usage is near the limit',
      autoStopNearFiveHourLimitHelp:
        'When the system detects that the account is close to the 5-hour usage limit, scheduling is paused automatically. Scheduling resumes in the next time window.',
      serialQueue: 'Enable account-level serial queue',
      serialQueueHelp:
        'Forces user messages for this account to be processed serially and ignores the global serial queue setting. Useful for accounts with low concurrency limits.',
      interceptWarmup: 'Intercept warmup requests',
      interceptWarmupHelp:
        'When enabled, low-value requests such as title generation and warmup return mock responses without consuming upstream API quota.',
      unifiedClaudeCodeVersion: 'Use unified Claude Code version',
      unifiedClaudeCodeVersionHelp:
        'Use a unified User-Agent captured from a real Claude Code client to improve compatibility.',
      currentUnifiedVersion: 'Current unified version: {version}',
      clearCache: 'Clear cache',
      clearingCache: 'Clearing...',
      waitingForUserAgent: 'Waiting to capture User-Agent from a Claude Code client',
      userAgentCaptureTip:
        'If capture takes too long, confirm that a Claude Code client is using this account or ask a developer to check whether the User-Agent format changed.',
      unifiedClientId: 'Use unified client identifier',
      unifiedClientIdHelp:
        'Use a fixed client identifier so all requests appear to come from the same client and reduce fingerprint variation.',
      clientId: 'Client identifier ID',
      regenerate: 'Regenerate',
      clientIdHelp:
        'This ID replaces the client part of user_id in requests while preserving the session part for sticky sessions.',
      priority: 'Scheduling priority (1-100)',
      priorityPlaceholder: 'Lower numbers have higher priority. Default is 50.',
      priorityEditPlaceholder: 'Lower numbers have higher priority',
      priorityHelp: 'Lower numbers have higher priority. Recommended range: 1-100.'
    },
    manualToken: {
      title: 'Enter token manually',
      claudeHelp:
        'Enter a valid Claude Access Token. If you have a Refresh Token, add it as well to support automatic refresh.',
      geminiHelp:
        'Enter a valid Gemini Access Token. If you have a Refresh Token, add it as well to support automatic refresh.',
      openaiHelp:
        'Enter a valid OpenAI Access Token. If you have a Refresh Token, add it as well to support automatic refresh.',
      droidHelp:
        'Enter a valid Droid Access Token and provide a Refresh Token to support automatic refresh.',
      howToGetAccessToken: 'How to get an Access Token:',
      claudeCredentialsBefore: 'Get credentials from',
      claudeCredentialsAfter:
        'on a machine logged in to Claude Code. Do not use keys from the Claude API Keys page.',
      geminiCredentialsBefore: 'Get credentials from',
      geminiCredentialsAfter: 'on a machine logged in to Gemini CLI.',
      openaiCredentialsHelp:
        'Get authentication credentials from a machine logged in to OpenAI, or use the OAuth authorization flow.',
      droidCredentialsHelp:
        'Get Access Token and Refresh Token from an authorized Droid CLI or Factory.ai export.',
      refreshTokenMissingHelp:
        'If Refresh Token is not provided, the token must be updated manually after it expires.',
      droidRefreshRequired:
        'Droid accounts must include a Refresh Token. Without it, Access Token refresh will fail.',
      accessTokenOptional: 'Access Token (optional)',
      accessTokenRequired: 'Access Token *',
      accessTokenOptionalPlaceholder:
        'Optional: if blank, the system automatically obtains it via Refresh Token...',
      accessTokenPlaceholder: 'Enter Access Token...',
      accessTokenOptionalHelp:
        'Access Token is optional. If omitted, the system obtains it automatically via Refresh Token.',
      refreshTokenRequired: 'Refresh Token *',
      refreshTokenOptional: 'Refresh Token (optional)',
      refreshTokenRequiredPlaceholder: 'Enter Refresh Token (required)...',
      refreshTokenPlaceholder: 'Enter Refresh Token...',
      openaiRefreshHelp:
        'The system uses Refresh Token to automatically obtain Access Token and user information.',
      droidRefreshHelp:
        'The system uses Refresh Token to automatically refresh Factory.ai access tokens and keep the account available.'
    },
    droidApiKey: {
      title: 'Use API Key to schedule Droid',
      help: 'Enter one or more Factory.ai API keys. The system randomly selects a key per request and uses session hashing for stickiness to keep conversation context stable.',
      list: 'API Key list *',
      listPlaceholder: 'One API Key per line. Multiple lines can be pasted.',
      listHelp:
        'Provide separate quota for each key. The system automatically deduplicates and ignores blank lines.',
      allocationTitle: 'Allocation policy',
      allocationNewSession:
        'New sessions randomly hit one key and stay sticky for the session lifetime.',
      allocationFallback:
        'If a key fails, the system automatically switches to remaining available keys to maximize success rate.',
      allocationAutoMark:
        'If upstream returns a 4xx error, that key is automatically marked abnormal. When all keys are abnormal, account scheduling is paused.',
      updateTitle: 'Update API Key',
      manage: 'Manage API Key',
      savedCount:
        '{count} API keys saved. You can append new keys below, or quickly replace or delete specific keys by mode.',
      blankKeepsExisting:
        'Leave blank to keep existing keys unchanged. The selected mode decides whether entered keys are appended, replaced, or deleted.',
      newList: 'New API Key list',
      newListPlaceholder: 'Fill according to the mode. One API Key per line.',
      updateMode: 'API Key update mode',
      appendMode: 'Append mode',
      appendDescription: 'Keep existing keys and append the new key list at the end.',
      replaceMode: 'Replace mode',
      replaceDescription: 'Clear old keys first, then write the new key list above.',
      deleteMode: 'Delete mode',
      deleteDescription:
        'Enter keys to remove. Useful for precisely deleting failed or banned keys.',
      tips: 'Tips',
      tipSticky:
        'The system automatically creates sticky mappings for new keys so the same session hits the same key.',
      tipAppend: 'Append mode keeps existing keys and appends new keys at the end.',
      tipReplace: 'Replace mode clears old keys before writing the new list above.',
      tipDelete: 'Delete mode precisely removes entered keys, useful for failed or banned keys.'
    },
    setupToken: {
      title: 'Claude Setup Token authorization',
      selectAuthMethod: 'Select authorization method:',
      manualAuth: 'Manual authorization',
      cookieAutoAuth: 'Cookie auto authorization',
      manualIntro: 'Follow these steps to authorize the Claude account with Setup Token:',
      generateLinkStep: 'Click the button below to generate an authorization link',
      generating: 'Generating...',
      generateLink: 'Generate Setup Token authorization link',
      copyLinkTitle: 'Copy link',
      regenerate: 'Regenerate',
      openLinkStep: 'Open the link in a browser and complete authorization',
      openLinkHelp:
        'Open the authorization link in a new tab, sign in to your Claude account, and authorize Claude Code.',
      noteLabel: 'Note:',
      proxyWarning:
        'If you configured a proxy, make sure your browser uses the same proxy to access the authorization page.',
      inputCodeStep: 'Enter Authorization Code',
      inputCodeHelp:
        'After authorization is complete, copy the Authorization Code from the return page and paste it below:',
      authCodePlaceholder:
        'Paste the Authorization Code from the Claude Code authorization page...',
      authCodeHelp: 'Paste the Authorization Code copied from the Claude Code authorization page',
      cookieIntro:
        'Use sessionKey to complete authorization automatically without opening the link manually.',
      sessionKeyCount: '{count}',
      sessionKeyPlaceholder:
        'One sessionKey per line, for example:\nsk-ant-sid01-xxxxx...\nsk-ant-sid01-yyyyy...',
      batchCreateCount: 'Will batch create {count} accounts',
      howToGetSessionKey: 'How to get sessionKey?',
      sessionKeyStep1: '1. Log in to claude.ai in your browser',
      sessionKeyStep2: '2. Press F12 to open developer tools',
      sessionKeyStep3: '3. Switch to the Application tab',
      sessionKeyStep4: '4. Select Cookies -> https://claude.ai on the left',
      sessionKeyStep5: '5. Find the row whose key is sessionKey',
      sessionKeyStep6: '6. Copy the content in its Value column',
      sessionKeyPrefixHelp: 'sessionKey usually starts with "sk-ant-"',
      authorizingProgress: 'Authorizing {current}/{total}...',
      authorizing: 'Authorizing...',
      startAutoAuth: 'Start auto authorization',
      cookieProxyTip:
        'If you configured a proxy, Cookie authorization also uses the same proxy configuration.',
      validating: 'Validating...',
      finishAuth: 'Finish authorization'
    },
    tokenUpdate: {
      title: 'Update token',
      help: 'You can update Access Token and Refresh Token. For security, current token values are not shown.',
      blankKeepsField: 'Leave blank to keep this field unchanged.',
      newAccessToken: 'New Access Token',
      newRefreshToken: 'New Refresh Token',
      blankNoUpdatePlaceholder: 'Leave blank to keep unchanged...'
    },
    validation: {
      accountNameRequired: 'Please enter an account name',
      groupRequired: 'Please select a group',
      apiUrlRequired: 'Please enter API URL',
      apiKeyRequired: 'Please enter API Key',
      apiBaseRequired: 'Please enter API base URL',
      apiSecretRequired: 'Please enter API key',
      awsAccessKeyIdRequired: 'Please enter AWS Access Key ID',
      awsSecretAccessKeyRequired: 'Please enter AWS Secret Access Key',
      bearerTokenRequired: 'Please enter Bearer Token',
      awsRegionRequired: 'Please select AWS region',
      azureEndpointRequired: 'Please enter Azure Endpoint',
      deploymentNameRequired: 'Please enter deployment name',
      refreshTokenRequired: 'Please enter Refresh Token',
      accessTokenRequired: 'Please enter Access Token',
      atLeastOneApiKeyRequired: 'Please enter at least one API Key',
      deleteApiKeyRequired: 'Please enter the API Key to delete',
      sessionKeyRequired: 'Please enter at least one sessionKey'
    },
    confirm: {
      defaultContinue: 'Continue',
      defaultCancel: 'Cancel',
      projectIdMissingTitle: 'Project ID is missing',
      projectIdMissingMessage:
        'You have not entered a project ID.\n\nIf your Google account is linked to Google Cloud or recognized as a Workspace account, a project ID is required.\nIf you are using a regular personal account, you can continue without one.',
      continue: 'Continue',
      continueSave: 'Continue saving',
      returnToFill: 'Go back and fill in'
    },
    toast: {
      setupTokenGenerateFailed: 'Failed to generate Setup Token authorization link',
      linkCopied: 'Link copied',
      copyFailedManual: 'Copy failed. Please copy manually.',
      setupTokenAuthFailed:
        'Setup Token authorization failed. Check whether the authorization code is correct.',
      allAuthFailed: 'All authorizations failed. Check whether sessionKey is valid.',
      authFailedCount: '{count} authorizations failed',
      createdBatch: 'Successfully created {created}/{total} accounts',
      accountCreated: 'Account created successfully',
      accountCreateFailed: 'Account creation failed',
      accountsCreateFailedCount: '{count} accounts failed to create',
      refreshTokenMissingAfterAuth:
        'Authorization succeeded but no Refresh Token was returned. Confirm offline access was granted and try again.',
      unsupportedPlatform: 'Unsupported platform: {platform}',
      accountUpdateFailed: 'Account update failed',
      details: 'Details: {details}',
      loadGroupsFailed: 'Failed to load group list',
      groupsRefreshed: 'Group list refreshed',
      extractAuthCodeSuccess: 'Authorization code extracted.',
      authCodeParamMissing:
        'No authorization code parameter found in the URL. Check whether the link is correct.',
      invalidUrl: 'Invalid link format. Check whether this is a complete URL.',
      requireLocalhostCallback: 'Paste a link starting with http://localhost:45462',
      modelMappingExists: 'Mapping for model {from} already exists',
      modelMappingAdded: 'Added mapping: {from} -> {to}',
      unifiedUserAgentCacheCleared: 'Unified User-Agent cache cleared',
      clearCacheFailed: 'Failed to clear cache',
      clearCacheFailedWithReason: 'Failed to clear cache: {reason}',
      unknownError: 'Unknown error',
      newClientIdGenerated: 'New client identifier generated'
    }
  }
}
